source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"

target '项目四' do

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJRefresh"
pod "DACircularProgress"
pod "pop"
pod "MJExtension"
pod "NJKWebViewProgress"

end
